export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const SEARCH_LIST = 'header/SEARCH_LIST'
export const SET_PAGE = 'header/SET_PAGE'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const SWITCH_PAGE = 'header/SWITCH_PAGE'

export const OPEN_ROTATE = 'header/OPEN_ROTATE'
export const CLOSE_ROTATE = 'header/CLOSE_ROTATE'
export const BLACK_THEME = 'header/BLACK_THEME'
export const WHITE_THEME = 'header/WHITE_THEME'
export const TOGGLE_THEME_BOX = 'header/TOGGLE_THEME_BOX'